import { describe, expect, it } from "vitest";
import { buildClientSchema, parse, validate } from "graphql";
import schemaJson from "./fixtures/app-schema.json";
import {
  ACTIVE_CONTRACT_QUERY,
  APPLY_PRESET_MUTATION,
  AUTO_RESPONDER_SETTINGS_QUERY,
  AVAILABILITY_QUERY,
  CALIBRATION_PROFILES_QUERY,
  COMPANY_QUERY,
  CREATE_CONTRACT_MUTATION,
  DIGEST_SUMMARIES_QUERY,
  DISMISS_DIGEST_ENTRY_MUTATION,
  EVALUATE_INTERRUPT_QUERY,
  LIST_PRESETS_QUERY,
  LIST_PROPOSALS_QUERY,
  OVERRIDE_VERDICT_MUTATION,
  PROFILE_QUERY,
  REPORT_OUTCOME_MUTATION,
  SCHEDULE_QUERY,
  SUBMIT_PROPOSAL_MUTATION,
  TEAM_PRESENCE_QUERY,
  TEAMS_QUERY,
  UPDATE_AUTO_RESPONDER_SETTINGS_MUTATION,
  UPDATE_VERDICT_SETTINGS_MUTATION,
  VERDICT_SETTINGS_QUERY,
} from "../src/queries.js";

const schema = buildClientSchema((schemaJson as { data?: unknown }).data ?? schemaJson);

const DOCUMENTS = [
  ["ACTIVE_CONTRACT_QUERY", ACTIVE_CONTRACT_QUERY],
  ["SCHEDULE_QUERY", SCHEDULE_QUERY],
  ["AVAILABILITY_QUERY", AVAILABILITY_QUERY],
  ["SUBMIT_PROPOSAL_MUTATION", SUBMIT_PROPOSAL_MUTATION],
  ["LIST_PROPOSALS_QUERY", LIST_PROPOSALS_QUERY],
  ["LIST_PRESETS_QUERY", LIST_PRESETS_QUERY],
  ["APPLY_PRESET_MUTATION", APPLY_PRESET_MUTATION],
  ["CREATE_CONTRACT_MUTATION", CREATE_CONTRACT_MUTATION],
  ["PROFILE_QUERY", PROFILE_QUERY],
  ["REPORT_OUTCOME_MUTATION", REPORT_OUTCOME_MUTATION],
  ["OVERRIDE_VERDICT_MUTATION", OVERRIDE_VERDICT_MUTATION],
  ["EVALUATE_INTERRUPT_QUERY", EVALUATE_INTERRUPT_QUERY],
  ["CALIBRATION_PROFILES_QUERY", CALIBRATION_PROFILES_QUERY],
  ["VERDICT_SETTINGS_QUERY", VERDICT_SETTINGS_QUERY],
  ["UPDATE_VERDICT_SETTINGS_MUTATION", UPDATE_VERDICT_SETTINGS_MUTATION],
  ["DIGEST_SUMMARIES_QUERY", DIGEST_SUMMARIES_QUERY],
  ["DISMISS_DIGEST_ENTRY_MUTATION", DISMISS_DIGEST_ENTRY_MUTATION],
  ["AUTO_RESPONDER_SETTINGS_QUERY", AUTO_RESPONDER_SETTINGS_QUERY],
  ["UPDATE_AUTO_RESPONDER_SETTINGS_MUTATION", UPDATE_AUTO_RESPONDER_SETTINGS_MUTATION],
  ["TEAMS_QUERY", TEAMS_QUERY],
  ["COMPANY_QUERY", COMPANY_QUERY],
  ["TEAM_PRESENCE_QUERY", TEAM_PRESENCE_QUERY],
] as const;

describe("GraphQL schema compatibility", () => {
  for (const [name, document] of DOCUMENTS) {
    it(`validates ${name} against the current app schema`, () => {
      const ast = parse(document);
      const errors = validate(schema, ast);
      expect(errors).toEqual([]);
    });
  }
});
